[PKB] Implemented unit tests for Parent and AST classes
mlnq/AITSI-M3SPIN pull request #14
Opened 2022-05-22 13:04 UTC by mati2806

2022-05-22 14:44 UTC, Milida requested changes
Po przejrzeniu kodu, wymaganych jest trochę poprawek. Część komentarzy została dodana przeze mnie, część przez Pawła, ale ze wszystkimi się zgadzam.

2022-05-22 14:44 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +                () -> assertEquals(EntityType.VARIABLE, ast.getType(variable)),
Albo rozbijamy wszystko na metody z pojedynczymi testami, albo robimy wszystko w jednej (wtedy testujemy wszystkie przypadki) tak jak w metodzie `createTNode`

2022-05-22 14:44 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +        ast.setName(variable, "y");
Tutaj `setName` powinno być zamienione na `setAttribute` wywoływane z `variable` jeśli chodzi nam o przetestowanie pojedynczej metody z AST

2022-05-22 14:44 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/ParentImplTest.java
> +    void setParent() {
Ta metoda powinna testować metodę `setParent` z interfejsu `Parent`, a nie jest ona tutaj używana.

2022-05-22 14:44 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/ParentImplTest.java
> +        assertEquals(parentMethods.getParent(child), parent);
Expected value powinno być `parent`, a actual value `child.getParent()`

2022-05-22 14:44 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/ParentImplTest.java
> +    void isParent() {
Ten test powinien chyba sprawdzać `isParent` z interfejsu `Parent`, ale ta metoda nie jest tu wykorzystywana.

2022-05-22 14:47 UTC, praglis requested changes
Przejrzeliśmy z razem z @Milida testy i trzeba kilka rzeczy poprawić. Na Discordzie przypięliśmy na kanale #info ogólne konwencje, których powinniśmy się wszyscy trzymać podczas pisania testów jednostkowych. Sorki, że nie napisaliśmy ich wcześniej, na pewno byś miał mniej poprawek 😅

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +            ast.setLink(LinkType.PARENT, node1, node2);
Raczej rozbić na 3 mniejsze testy

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +        assertEquals(ast.getRoot(), root);
Powinno być:
expected value: zmienna `root`
actual value: to co zwróci `setRoot()`

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +            ast.setLink(LinkType.PARENT, node1, node2);
Też raczej do rozbicia na 3 testy

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +            ast.setLink(LinkType.PARENT, node1, node2);
Raczej na 3 testy

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/ParentImplTest.java
> +        assertEquals(parentMethods.getParent(child), parent);
Zamienić kolejność argumentów

2022-05-22 14:47 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/ParentImplTest.java
> +        throw new NotImplementedException();
Niezaimplemenowane testy nie powinny się wywalać. Są 2 możliwe rozwiązania:
1) zamiast wyrzucać exception dać komentarz `todo`
2) usunąć/zakomentować cały test

2022-05-22 15:02 UTC, praglis commented
Jeszcze jedno: w Javie testy powinny być w pakietach:
src/**test**/java/aitsi/m3spin/...
a nie
src/**main**/java/aitsi/m3spin/...

src/main jest do kodu, src/test do testów

2022-06-06 21:50 UTC, Milida commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +        Variable variable = new VariableImpl(0);
Czeka na scalenie #23

2022-06-06 21:53 UTC, Milida commented
Czeka na scalenie #23

2022-06-07 09:39 UTC, praglis requested changes
Poprawia Ida

2022-06-07 09:39 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +        Variable variable = new VariableImpl(0);
Czeka na scalenie #23

2022-06-07 10:12 UTC, praglis approved these changes
Można scalać, kolejne testy doda się w nowym PR-ze. Poprawka testów atrybutów do napisania po scaleniu #23 (dopisałem info na Trello)

2022-06-07 10:13 UTC, praglis commented on src/main/java/aitsi/m3spin/tests/AstImplTest.java
> +        Variable variable = new VariableImpl(0);
Zamykam, dodałem punkt w ATS-9 na Trello

2022-06-07 10:14 UTC, Milida approved these changes
Jest okej

2022-06-07 10:14 UTC, merged