Implementacja zapisu sparsowanych informacji do PKB dla iteracji 1
mlnq/AITSI-M3SPIN pull request #8
Opened 2022-04-26 14:28 UTC by praglis

2022-05-05 12:20 UTC, Milida requested changes
Parę rzeczy jest jeszcze do poprawienia, ale to raczej drobnostki.

2022-05-05 17:25 UTC, praglis commented on src/aitsi/m3spin/pkb/impl/AstImpl.java
> +    public void setName(TNode n, String attr) {
Skoro to będzie podjęte w zadaniu #18, to możemy zamknąć tę nitkę?

2022-05-05 17:25 UTC, praglis commented on src/aitsi/m3spin/pkb/interfaces/Ast.java
> -    /**
Dokumentacja oberwała przypadkiem przy rozwiązywaniu konfliktów 😅 Naprawię

2022-05-05 18:29 UTC, praglis commented
Odnosząc się do dzisiejszej (5 V 2022) dyskusji z Jarząbkiem o Parserze i Design Extractorze: przenieść mam te wszystkie metody `fillPkb()` do Design Extractora?

2022-05-05 18:33 UTC, praglis commented on src/aitsi/m3spin/spafrontend/parser/Parser.java
> +        pkb.getProcTable().insertProc(procedure.getName());
Pytanie, czy nie będą potrzebne, jak podzielimy klasy z `commons` wg zadania #18 🤔

2022-05-05 18:54 UTC, Milida commented on src/aitsi/m3spin/pkb/impl/AstImpl.java
> +    public void setName(TNode n, String attr) {
W takim razie zamykam.

2022-05-05 19:25 UTC, Milida commented on src/aitsi/m3spin/spafrontend/parser/Parser.java
> +        pkb.getProcTable().insertProc(procedure.getName());
Ta kwestia będzie do przedyskutowania po wykonaniu zadania #18. Tutaj zamykam wątek.

2022-05-05 19:26 UTC, Milida approved these changes
Moim zdaniem wszystko wygląda już dobrze.

2022-05-07 10:25 UTC, mati2806 approved these changes
Jest git

2022-05-07 16:44 UTC, praglis commented
> Odnosząc się do dzisiejszej (5 V 2022) dyskusji z Jarząbkiem o Parserze i Design Extractorze: przenieść mam te wszystkie metody `fillPkb()` do Design Extractora? @Milida

Będzie realizowane w osobnym zadaniu #14

2022-05-07 16:45 UTC, merged